# Generated by Django 3.0.4 on 2020-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
